<?php
// $Id$

/**
 * Implementation of hook_autoload_info().
 */
function conglomerate_autoload_info() {
  return array(
    'ConglomerateContentResource' => array(
      'file' => 'ConglomerateContentResource.php',
    ),
    'ConglomerateContentFeedModel' => array(
      'file' => 'ConglomerateContentFeedModel.php',
    ),
  );
}

/**
 * Implementation of hook_service_resource().
 */
function conglomerate_service_resource() {
  $res = array(
    // Conglomerate resource
    'conglomerate-content' => ServicesOop::definitionFromClass('ConglomerateContentResource'),
  );
  return $res;
}

function conglomerate_oauth_default_contexts() {
  return array(
    'conglomerate' => array(
      '*' => array(
        'title' => 'Yes, I want to connect !appname to !sitename',
        'description' => 'This will allow your site !appname to push content to !sitename',
        'weight' => -1,
      ),
      'read' => array(
        'title' => 'I want to connect, but just to get stuff from !sitename',
        'description' => 'This will allow !appname to fetch content from !sitename, but it will not allow any information to be pushed to !sitename.',
        'weight' => 0,
      ),
    )
  );
}

/**
 * Implementation of hook_services_contexts().
 */
function conglomerate_services_contexts() {
  return array(
    'conglomerate' => array(
      'title' => 'Conglomerate API',
      'server' => 'rest_server',
      'path' => 'api',
      'authentication' => 'services_oauth',
      'authentication_settings' => array(
        'oauth_context' => 'conglomerate',
      ),
      'resources' => array(
        'conglomerate-content' => array(
          'alias' => 'content',
          'operations' => array(
            'create' => array(
              'enabled' => TRUE,
              'oauth_credentials' => 'token',
              'oauth_authorization' => '*',
            ),
            'retrieve' => array(
              'enabled' => TRUE,
              'oauth_credentials' => 'unsigned_consumer',
              'oauth_authorization' => 'read',
            ),
            'update' => array(
              'enabled' => TRUE,
              'oauth_credentials' => 'token',
              'oauth_authorization' => '*',
            ),
            'delete' => array(
              'enabled' => TRUE,
              'oauth_credentials' => 'token',
              'oauth_authorization' => '*',
            ),
            'index' => array(
              'enabled' => TRUE,
              'oauth_credentials' => 'unsigned_consumer',
              'oauth_authorization' => 'read',
            ),
          ),
        ),
        'solr' => array(
          'alias' => 'search',
          'operations' => array(
            'index' => array(
              'enabled' => TRUE,
              'preprocess' => '_conglomerate_modify_solr_search',
              'oauth_credentials' => 'unsigned_consumer',
              'oauth_authorization' => 'read',
            ),
          )
        ),
      ),
    ),
  );
}

function _conglomerate_modify_solr_search(&$parameters) {
  // Do stuff to enforce sensible restrictions
}